#define LCD_I2C_ADDRESS 0x20

#define SUCCESS_SHOW_TIME 5000
#define RESULT_DELAY      3000
#define BUZZER_PIN  A0
#define RESULT_KEY  A1
#define RESET_BTN    A2
#define READY_LED   A3

#define CANDIDATE_1 "CAND1"
#define CANDIDATE_2 "CAND2"
#define CANDIDATE_3 "CAND3"
#define CANDIDATE_4 "CAND4"
#define CANDIDATE_5 "CAND5"
#define CANDIDATE_6 "CAND6"
#define CANDIDATE_7 "CAND7"
#define CANDIDATE_8 "CAND8"
#define CANDIDATE_9 "CAND9"
#define CANDIDATE_10 "CAND10"